const express = require('express');
const { router: auth } = require('../modules/auth/auth.routes');
const { router: dashboard } = require('../modules/dashboard/dashboard.routes');
const { router: patients } = require('../modules/patients/patient.routes');
const { router: doctors } = require('../modules/doctors/doctor.routes');
const { router: services } = require('../modules/services/service.routes');
const { router: pricing } = require('../modules/pricing/pricing.routes');
const { router: schedules } = require('../modules/schedules/schedule.routes');
const { router: appointments } = require('../modules/appointments/appointment.routes');
const { router: queue } = require('../modules/queue/queue.routes');
const { router: cases } = require('../modules/cases/case.routes');
const { router: visits } = require('../modules/visits/visit.routes');
const { router: pregnancy } = require('../modules/pregnancy/pregnancy.routes');
const { router: medications } = require('../modules/medications/medication.routes');
const { router: allergies } = require('../modules/allergies/allergy.routes');
const { router: labs } = require('../modules/labs/lab.routes');
const { router: ultrasound } = require('../modules/ultrasound/ultrasound.routes');
const { router: documents } = require('../modules/documents/document.routes');
const { router: progress } = require('../modules/progress/progress.routes');
const { router: reports } = require('../modules/reports/report.routes');
const { router: notifications } = require('../modules/notifications/notification.routes');
const { router: users } = require('../modules/users/user.routes');
const { router: settings } = require('../modules/settings/setting.routes');
const { router: audit } = require('../modules/audit/audit.routes');
const { router: history } = require('../modules/history/history.routes');
const { router: publicRoutes } = require('../modules/public/public.routes');
const { router: patientPortal } = require('../modules/patient-portal/patient-portal.routes');

const apiRouter = express.Router();
apiRouter.use('/auth', auth);
apiRouter.use('/dashboard', dashboard);
apiRouter.use('/patients', patients);
apiRouter.use('/doctors', doctors);
apiRouter.use('/services', services);
apiRouter.use('/pricing', pricing);
apiRouter.use('/schedules', schedules);
apiRouter.use('/appointments', appointments);
apiRouter.use('/queue', queue);
apiRouter.use('/cases', cases);
apiRouter.use('/visits', visits);
apiRouter.use('/pregnancies', pregnancy);
apiRouter.use('/medications', medications);
apiRouter.use('/allergies', allergies);
apiRouter.use('/labs', labs);
apiRouter.use('/ultrasounds', ultrasound);
apiRouter.use('/documents', documents);
apiRouter.use('/progress', progress);
apiRouter.use('/reports', reports);
apiRouter.use('/notifications', notifications);
apiRouter.use('/users', users);
apiRouter.use('/settings', settings);
apiRouter.use('/audit', audit);
apiRouter.use('/medical-history', history);
apiRouter.use('/public', publicRoutes);
apiRouter.use('/patient-portal', patientPortal);

module.exports = { apiRouter };
